[package]
name = "rastra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bytes = "1.5.0"
rand = "0.8.5"
uuid = "1.6.1"
compress = { version = "0.2.1", features = ["flate"] }
base64 = "0.21.5"
varint-rs = { version = "2.2.0", features = ["signed", "default"]}
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }
lazy_static = "1.4"
async_once = "0.2.6"

[dependencies.rust-raknet]
path = "src/raknet"

