ip = "127.0.0.1"
port_v4 = 19132
port_v6 = 19133

name = "my server"
motd = "my motd"

compression = "Flate"

auto_update_current_players = true
max_players = 100

debug_messages = true

protocol_version = 630
force_protocol_version = false
protocol_edition = "MCPE"

game_version = "1.20.51"
force_version = false