name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Rust x86_64-pc-windows-msvc
      run: rustup target add x86_64-pc-windows-msvc
      
    - name: Build x86_64-pc-windows-msvc
      run: cargo build --bin=RAstra --release --target=x86_64-pc-windows-msvc
      
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: java-artifact
        path: target/x86_64-pc-windows-msvc/release/*.exe
